name: "🐞 Bug Report"
description: "Report bugs to fix Vulcan Docs"
title: "[BUG] <short title>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thank you for reporting the bug! Please fill in the following details.."

  - type: input
    id: contact
    attributes:
      label: "Contact (optional)"
      description: "Email/Telegram/GitHub if you want to be contacted"
      placeholder: "your@email.com"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Bug description"
      description: "Tell me what happened"
      placeholder: "The bug appears when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction steps"
      description: "Clear steps to surface the bug"
      placeholder: |
        1. Open page...
        2. Click the button...
        3. See error..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      placeholder: "What should happen is..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Log / screenshot (optional)"
      description: "Please attach a screenshot or error log if any"
    validations:
      required: false